server:
  port: 8081
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: name
      password: password 
  jpa:
   hibernate:
      ddl-auto: update
   show-sql: true
   database-platform: org.hibernate.dialect.MySQL8Dialect
   properties:
      '[hibernate.format_sql]': true
      
logging:
  file:
    name: log/studentapp.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    '[org.springframework.web]': WARN
    '[org.hibernate]': INFO
    '[com.tpro]': INFO
    
management:   # actuator
  endpoints:
    web:
      exposure:
        include: ['health','loggers','env','beans']        
    
    
    
    
    
    
    
    
    
    